export const sampleMovies = [
  {
    id: 1,
    title: "Squid Game",
    overview: "Hundreds risk death for riches in a twisted survival competition.",
    image: "https://images.ctfassets.net/4cd45et68cgf/6xlqqImDdAfzWKIlaScQxm/7def051f35d6668bd6e6227e354ecc01/EN-US_SG-S2_Primary_Main_RoundandRound-Safe_Vertical_27x40_RGB_PRE.jpg",
    category: "Trending Now",
  },
  {
    id: 2,
    title: "Wednesday",
    overview: "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student.",
    image: "https://i.redd.it/u1z7t2knpjra1.jpg",
    category: "New Releases",
  },
  {
    id: 3,
    title: "Queen of Tears",
    overview: "The queen of department stores and her small-town husband weather a marital crisis — until love miraculously begins to bloom again.",
    image: "https://images.ctfassets.net/4cd45et68cgf/Rb6wz7UfbWMR26SsqxxJL/82ba4eb884c1b2ca426a2b250d8afa86/ENUS_QueenofTears-Hae-In_CharacterKA_Vertical_RGB_PRE.jpg_ENUS_QueenofTears-Hae-In_CharacterKA_Vertical_RGB_PRE.jpg",
    category: "Top Picks",
  },
  {
    id: 4,
    title: "It's Okay to Not Be Okay",
    overview: "An unusual romance between a psychiatric ward caretaker and a fairy tale writer.",
    image: "https://upload.wikimedia.org/wikipedia/en/5/58/It%27s_Okay_to_Not_Be_Okay_Poster.jpg",
    category: "Critically Acclaimed",
  },
  {
    id: 5,
    title: "Money Heist",
    overview: "A group of robbers assault the Factory of Moneda and Timbre.",
    image: "https://m.media-amazon.com/images/M/MV5BZjkxZWJiNTUtYjQwYS00MTBlLTgwODQtM2FkNWMyMjMwOGZiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Action",
  },
  {
    id: 6,
    title: "When Your Phone Rings",
    overview: "A love letter to the '80s classics that captivated a generation.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNhkl3XwZ2j5ScgxlkX6M2rzHdJsObIVh86PpxmNkYtJAW-AUP",
    category: "Trending Now",
  },
  {
    id: 7,
    title: "The Crown",
    overview: "The gripping, decades-spanning inside story of Her Majesty Queen Elizabeth II.",
    image: "https://images.unsplash.com/photo-1465165665848-e9a3c2631f94?auto=format&fit=crop&w=400&q=80",
    category: "Trending Now",
  },
  {
    id: 8,
    title: "Bridgerton",
    overview: "Wealth, lust, and betrayal set in Regency-era England.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    category: "New Releases",
  },
  {
    id: 9,
    title: "Extraction",
    overview: "A black-market mercenary embarks on the deadliest extraction of his career.",
    image: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1?auto=format&fit=crop&w=400&q=80",
    category: "Action",
  },
  {
    id: 10,
    title: "The Witcher",
    overview: "The witcher Geralt, a mutated monster hunter, struggles to find his place in the world.",
    image: "https://images.unsplash.com/photo-1706743939268-de0d24e0f7c9?auto=format&fit=crop&w=400&q=80",
    category: "Top Picks",
  },
  {
    id: 11,
    title: "Breaking Bad",
    overview: "A high school chemistry teacher turned methamphetamine producer...",
    image: "https://images.unsplash.com/photo-1464029902023-f42eba355bde?auto=format&fit=crop&w=400&q=80",
    category: "Critically Acclaimed",
  },
  {
    id: 12,
    title: "Avengers: Endgame",
    overview: "After the devastating events of Infinity War, the universe is in ruins...",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3769?auto=format&fit=crop&w=400&q=80",
    category: "Action",
  },
  {
    id: 13,
    title: "What/If",
    overview: "A dangerous, charming man goes to extreme measures for love.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQNAYFJ4jH6MPLCmlIGBrEMd2OsxDKgEZU7OyEzCFbU5KGn-WiC&psig=AOvVaw1820taSMUpTMxperiYPOrn&ust=1747408983072000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCLDG2_3jpY0DFQAAAAAdAAAAABAE",
    category: "Top Picks",
  },
  {
    id: 14,
    title: "Lucifer",
    overview: "The original fallen angel retires to L.A. and runs a club.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn2.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQtbTZBItahxy_CaaA11vjtTNSM6u18SgifrWdztqv8SfIjI4k_&psig=AOvVaw1Y6S6Df9u804QTIqGuR08k&ust=1747409073655000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCNj-3JrkpY0DFQAAAAAdAAAAABAE",
    category: "Top Picks",
  },
  {
    id: 15,
    title: "Narcos",
    overview: "Meet the men who would stop Pablo Escobar and the Medellín Cartel.",
    image: "https://images.unsplash.com/photo-1454023492550-5696f8ff10e1?auto=format&fit=crop&w=400&q=80",
    category: "Critically Acclaimed",
  },
  {
    id: 16,
    title: "King The Land",
    overview: "Amid a tense inheritance fight, a charming heir clashes with his hardworking employee who's known for her irresistible smile — which he cannot stand.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.justwatch.com%2Fin%2Ftv-show%2Fking-the-land%2Fseason-1&psig=AOvVaw1EluyEEHnOrJ1FhtOjmNx0&ust=1747409535370000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCPiYkvblpY0DFQAAAAAdAAAAABAE",
    category: "Trending Now",
  },
  {
    id: 17,
    title: "Peaky Blinders",
    overview: "A gangster family epic set in 1919 Birmingham.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn2.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQlXYTWdFgKPpuRtDYwLWWFmIk8RyoMj7wxNrB9wygwvOhkp3xx&psig=AOvVaw0hpmP7Ysy0eN7e70wVOCyw&ust=1747409225453000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCJCbp-PkpY0DFQAAAAAdAAAAABAE",
    category: "Critically Acclaimed",
  },
  {
    id: 18,
    title: "My Demon",
    overview: "Sherlock’s teen sister embarks on adventures in Victorian London.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMy_Demon&psig=AOvVaw1zJe_E5-6pI3huY3ArxGeD&ust=1747409261372000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCPj-9vbkpY0DFQAAAAAdAAAAABAE",
    category: "New Releases",
  },
  {
    id: 19,
    title: "XO, Kitty",
    overview: "Teen matchmaker Kitty Song Covey thinks she knows everything about love. But when she moves halfway across the world to reunite with her long-distance boyfriend, she'll soon realize that relationships are a lot more complicated when it's your own heart on the line.",
    image: "https://static1.tribute.ca/poster/660x980/xo-kitty-netflix-169453.jpg",
    category: "New Releases",
  },
  {
    id: 20,
    title: "Lucky Bhaskar",
    overview: "A gripping story about the extraordinary rise of an ordinary bank cashier in 1980s India.",
    image: "https://upload.wikimedia.org/wikipedia/en/6/6c/Lucky_Baskhar_film_poster.jpg",
    category: "Top Picks",
  },
  {
    id: 21,
    title: "Yeh Jawaani Hai Deewani",
    overview: "Bunny and Naina, along with two other friends, embark on a journey of friendship, love, and self-discovery as they travel together and experience adventures, heartbreak, and fun.",
    image: "https://m.media-amazon.com/images/M/MV5BODA4MjM2ODk4OF5BMl5BanBnXkFtZTcwNDgzODk1OQ@@._V1_FMjpg_UX1000_.jpg",
    category: "Top Picks",
  },
  {
    id: 22,
    title: "Knock Off",
    overview: "Kim Soo-hyun stars in this highly anticipated Netflix film about secrets, imposters, and a shocking conspiracy. Coming soon!",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRYdE-zeZqfJCaaFtzp3OPcbq_XCNjV1ReWg1AW4-kxBjCcX9-M",
    category: "Coming Soon",
  },
  {
    id: 23,
    title: "Vincenzo",
    overview: "During a visit to his motherland, a Korean-Italian Mafia lawyer gives an unrivaled conglomerate a taste of its own medicine with a side of justice.",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTaD6zet1fGlmjQQrSI0QXW-IzJ4H9LkrbpD7C-gfXdmiJ6IeUx",
    category: "Trending Now",
  },
];

export const categories = [
  "Trending Now",
  "Top Picks",
  "Action",
  "New Releases",
  "Critically Acclaimed",
  "Coming Soon",
];

