export const sampleMovies = [
  {
    id: 1,
    title: "Squid Game",
    overview: "Hundreds risk death for riches in a twisted survival competition.",
    image: "https://images.ctfassets.net/4cd45et68cgf/6xlqqImDdAfzWKIlaScQxm/7def051f35d6668bd6e6227e354ecc01/EN-US_SG-S2_Primary_Main_RoundandRound-Safe_Vertical_27x40_RGB_PRE.jpg",
    category: "Trending Now",
  },
  {
    id: 2,
    title: "Wednesday",
    overview: "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student.",
    image: "https://i.redd.it/u1z7t2knpjra1.jpg",
    category: "New Releases",
  },
  {
    id: 3,
    title: "Queen of Tears",
    overview: "The queen of department stores and her small-town husband weather a marital crisis — until love miraculously begins to bloom again.",
    image: "https://images.ctfassets.net/4cd45et68cgf/Rb6wz7UfbWMR26SsqxxJL/82ba4eb884c1b2ca426a2b250d8afa86/ENUS_QueenofTears-Hae-In_CharacterKA_Vertical_RGB_PRE.jpg_ENUS_QueenofTears-Hae-In_CharacterKA_Vertical_RGB_PRE.jpg",
    category: "Top Picks",
  },
  {
    id: 4,
    title: "It's Okay to Not Be Okay",
    overview: "An unusual romance between a psychiatric ward caretaker and a fairy tale writer.",
    image: "https://upload.wikimedia.org/wikipedia/en/5/58/It%27s_Okay_to_Not_Be_Okay_Poster.jpg",
    category: "Critically Acclaimed",
  },
  {
    id: 5,
    title: "Money Heist",
    overview: "A group of robbers assault the Factory of Moneda and Timbre.",
    image: "https://m.media-amazon.com/images/M/MV5BZjkxZWJiNTUtYjQwYS00MTBlLTgwODQtM2FkNWMyMjMwOGZiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Action",
  },
  {
    id: 6,
    title: "When Your Phone Rings",
    overview: "A love letter to the '80s classics that captivated a generation.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNhkl3XwZ2j5ScgxlkX6M2rzHdJsObIVh86PpxmNkYtJAW-AUP",
    category: "Trending Now",
  },
  {
    id: 7,
    title: "Real",
    overview: "A criminal aspiring to build a casino finds himself in endless threat when a man starts imitating every single thing he does.",
    image: "https://i.pinimg.com/736x/39/c7/f2/39c7f22c06238fd31d78eb473d883180.jpg",
    category: "Trending Now",
  },
  {
    id: 8,
    title: "War",
    overview: "A secret agent goes rogue after a mission to catch a terrorist goes awry. However, his boss sends Khalid, another agent and his student, to track him down.",
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQsHHM8pzbFQVcRVeys4kD1tnGA_dywwagbY8SJi-_NwZQxf-Rt",
    category: "Action",
  },
  {
    id: 9,
    title: "Court",
    overview: "A driven attorney battles a corrupt justice system to defend a young man whose relationship with a 17-year-old girl provokes her ruthless family's ire.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn3.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcSCv5-y9DhS8q0U-rbpnXkuwclO0fWZp7ozSYpRrN0FmgHDnUe3&psig=AOvVaw3wHIgfS_9o6rZVVhhQhoO6&ust=1747492773127000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCJDw04CcqI0DFQAAAAAdAAAAABAE",
    category: "Coming Soon",
  },
  {
    id: 10,
    title: "URI : The Surgical Strike",
    overview: "Indian army special forces execute a covert operation, avenging the killing of fellow army men at their base by a terrorist group.",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSHvgulsbkwf4qzDU4E_ofYWYBVXuKW16sw70QAp8iITBXB56Ee",
    category: "Top Picks",
  },
  {
    id: 11,
    title: "Chaava",
    overview: "After the death of his father, warrior-king Sambhaji Maharaj battles Mughal forces led by Aurangzeb to keep the Maratha Empire alive.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn2.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcRuWWDMeE1iElPRz-2r6jMLvYaOgHTrNWxHIC_7S9QmoZdDa8kO&psig=AOvVaw15NSvSAjPLGlZ-m8Mi5jCh&ust=1747492669055000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCMjI_s-bqI0DFQAAAAAdAAAAABAE",
    category: "Critically Acclaimed",
  },
  {
    id: 12,
    title: "One Ordinary Day",
    overview: "A remake of the BBC drama Criminal Justice that delves into the criminal justice system through the story of two men surrounding a woman's murder.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcTmbMKxgbbjXolTnnOqGcvHX0wZGQonr7E0Ci92HoFMFQyMdueY&psig=AOvVaw3fCm0T7v0nT_ugXePWFggw&ust=1747492986446000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCPjD1uacqI0DFQAAAAAdAAAAABAq",
    category: "Action",
  },
  {
    id: 13,
    title: "What/If",
    overview: "A dangerous, charming man goes to extreme measures for love.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQNAYFJ4jH6MPLCmlIGBrEMd2OsxDKgEZU7OyEzCFbU5KGn-WiC&psig=AOvVaw1820taSMUpTMxperiYPOrn&ust=1747408983072000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCLDG2_3jpY0DFQAAAAAdAAAAABAE",
    category: "Top Picks",
  },
  {
    id: 14,
    title: "Lucifer",
    overview: "The original fallen angel retires to L.A. and runs a club.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn2.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQtbTZBItahxy_CaaA11vjtTNSM6u18SgifrWdztqv8SfIjI4k_&psig=AOvVaw1Y6S6Df9u804QTIqGuR08k&ust=1747409073655000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCNj-3JrkpY0DFQAAAAAdAAAAABAE",
    category: "Top Picks",
  },
  {
    id: 15,
    title: "The Royals",
    overview: "When charming Prince Aviraaj meets Sophia, a self-made girl boss, the worlds of royalty and startups collide in a whirlwind of romance and ambition.",
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRMQxaFrNt9_HMz9irvaSEVefRA5B3yAICqYDuJRTK_TunNy3YR",
    category: "Critically Acclaimed",
  },
  {
    id: 16,
    title: "King The Land",
    overview: "Amid a tense inheritance fight, a charming heir clashes with his hardworking employee who's known for her irresistible smile — which he cannot stand.",
    image: "https://i.pinimg.com/736x/69/c1/49/69c149ba0ab99fa3a9bc24c762939e03.jpg",
    category: "Trending Now",
  },
  {
    id: 17,
    title: "Peaky Blinders",
    overview: "A gangster family epic set in 1919 Birmingham.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn2.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQlXYTWdFgKPpuRtDYwLWWFmIk8RyoMj7wxNrB9wygwvOhkp3xx&psig=AOvVaw0hpmP7Ysy0eN7e70wVOCyw&ust=1747409225453000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCJCbp-PkpY0DFQAAAAAdAAAAABAE",
    category: "Critically Acclaimed",
  },
  {
    id: 18,
    title: "My Demon",
    overview: "A pitiless demon becomes powerless after getting entangled with an icy heiress, who may hold the key to his lost abilities — and his heart.",
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fencrypted-tbn1.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcT65MwP6tuWN0Of54BLHRtRS1U2zJeDxRVoL18PVH5SDucwsVOi&psig=AOvVaw3QaNNd3Fswfu7PaWDkebLn&ust=1747492206014000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCIiy7fKZqI0DFQAAAAAdAAAAABAX",
    category: "New Releases",
  },
  {
    id: 19,
    title: "XO, Kitty",
    overview: "Teen matchmaker Kitty Song Covey thinks she knows everything about love. But when she moves halfway across the world to reunite with her long-distance boyfriend, she'll soon realize that relationships are a lot more complicated when it's your own heart on the line.",
    image: "https://static1.tribute.ca/poster/660x980/xo-kitty-netflix-169453.jpg",
    category: "New Releases",
  },
  {
    id: 20,
    title: "Lucky Bhaskar",
    overview: "A gripping story about the extraordinary rise of an ordinary bank cashier in 1980s India.",
    image: "https://upload.wikimedia.org/wikipedia/en/6/6c/Lucky_Baskhar_film_poster.jpg",
    category: "Top Picks",
  },
  {
    id: 21,
    title: "Yeh Jawaani Hai Deewani",
    overview: "Bunny and Naina, along with two other friends, embark on a journey of friendship, love, and self-discovery as they travel together and experience adventures, heartbreak, and fun.",
    image: "https://m.media-amazon.com/images/M/MV5BODA4MjM2ODk4OF5BMl5BanBnXkFtZTcwNDgzODk1OQ@@._V1_FMjpg_UX1000_.jpg",
    category: "Top Picks",
  },
  {
    id: 22,
    title: "Knock Off",
    overview: "Kim Soo-hyun stars in this highly anticipated Netflix film about secrets, imposters, and a shocking conspiracy. Coming soon!",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRYdE-zeZqfJCaaFtzp3OPcbq_XCNjV1ReWg1AW4-kxBjCcX9-M",
    category: "Coming Soon",
  },
  {
    id: 23,
    title: "Vincenzo",
    overview: "During a visit to his motherland, a Korean-Italian Mafia lawyer gives an unrivaled conglomerate a taste of its own medicine with a side of justice.",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTaD6zet1fGlmjQQrSI0QXW-IzJ4H9LkrbpD7C-gfXdmiJ6IeUx",
    category: "Trending Now",
  },
];

export const categories = [
  "Trending Now",
  "Top Picks",
  "Action",
  "New Releases",
  "Critically Acclaimed",
  "Coming Soon",
];

